language: java
install: true
sudo: true
cache:
    directories:
        - $HOME/.gradle
        - .gradle/
        - testfixtures/offline-repo/build/root

before_script:
    - ./gradlew --version

script:
    - ./gradlew --console=plain --warning-mode=all --scan -Dorg.gradle.parallel=true build jacocoRootReport

jdk:
    - openjdk8
    - openjdk10
    - openjdk11

after_success:
    - ./gradlew coveralls
