language: java

install: true

cache:
    directories:
        - $HOME/.gradle
        - .gradle/
        - testfixtures/offline-repo/build/root

before_script:
    - ./gradlew --version

script:
    - ./gradlew --console=plain --warning-mode=all build jacocoRootReport

jdk:
    - openjdk8
    - oraclejdk10
#    - openjdk9
#    - oraclejdk9

after_success:
    - ./gradlew coveralls
