name: Push documentation
on:
  push:
    branches:
      - master
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: zulu
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - run: cd docs
      - name: Combine documentation
        run: ./gradlew --console=plain -q combineDocs
      - name: Publish documentation
        run: ./gradlew --console=plain --info :antora:publishDocs :gh-pages:publishDocs
          -Dorg.ajoberstar.grgit.auth.username=${{ secrets.GITHUB_PUBLISH_USER }}
          -Dorg.ajoberstar.grgit.auth.password=${{ secrets.GITHUB_PUBLISH_KEY }}
          -Dorg.ajoberstar.grgit.auth.force=hardcoded
